# Generated by Django 2.1 on 2018-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('arch_name', models.CharField(max_length=60)),
                ('root_dir', models.CharField(max_length=60)),
            ],
        ),
    ]
