# Generated by Django 2.1 on 2018-08-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archs',
            name='id',
        ),
        migrations.AlterField(
            model_name='archs',
            name='arch_name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
