# Generated by Django 2.1 on 2018-08-31 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0002_auto_20180831_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archs',
        ),
    ]
