# Generated by Django 2.1 on 2018-08-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pydb_webapp', '0003_delete_archs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archs',
            fields=[
                ('index', models.IntegerField()),
                ('arch_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('root_dir', models.CharField(max_length=60)),
            ],
        ),
    ]
