# Generated by Django 2.1 on 2018-08-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0004_archs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archs',
        ),
    ]
