# Generated by Django 2.1 on 2018-09-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0006_archs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archs',
            name='id_archs',
        ),
    ]
