# Generated by Django 2.1 on 2018-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0007_remove_archs_id_archs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorys',
            fields=[
                ('dir_name', models.CharField(default='no_dir', max_length=60, primary_key=True, serialize=False)),
                ('arch', models.CharField(default='none', max_length=60)),
                ('root_dir', models.CharField(default='none', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='imgfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ImageField(default='none.img', upload_to='img')),
                ('arch', models.CharField(default='none', max_length=60)),
                ('outer', models.CharField(default='none', max_length=10)),
                ('site', models.CharField(default='none', max_length=10)),
                ('location', models.CharField(default='none', max_length=10)),
                ('content', models.CharField(default='none', max_length=10)),
                ('rmch_type', models.CharField(default='none', max_length=10)),
                ('description', models.CharField(default='none', max_length=255)),
                ('drawing_num', models.CharField(default='none', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='archs',
            name='arch_name',
            field=models.CharField(default='no_arch', max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archs',
            name='root_dir',
            field=models.CharField(default='\\', max_length=60),
        ),
    ]
