# Generated by Django 2.1 on 2018-09-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0008_auto_20180902_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directorys',
            new_name='Directories',
        ),
    ]
