# Generated by Django 2.1 on 2018-09-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0009_auto_20180902_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgfiles',
            old_name='rmch_type',
            new_name='nmch_type',
        ),
    ]
