# Generated by Django 2.1 on 2018-09-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0010_auto_20180903_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgfiles',
            name='p_or_d',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
