# Generated by Django 2.1 on 2018-09-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0011_imgfiles_p_or_d'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directories',
        ),
    ]
