# Generated by Django 2.1 on 2018-09-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0012_delete_directories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(default='none', max_length=60)),
                ('arch', models.CharField(default='none', max_length=60)),
                ('root_dir', models.CharField(default='none', max_length=60)),
            ],
        ),
    ]
