# Generated by Django 2.1.1 on 2018-09-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb_webapp', '0013_directories'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgfiles',
            name='root_dir',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
